### ISSUE TITLE
Setup a Build using kodo

### ISSUE THREAD

**Issue by sbose78** [cli-playground/kodo#15]
### What

Optionally support building from source:
```
kodo build --source=https://github.com/my/app 
```

### How

Assumption: The source code repo already has a Dockerfile. Example: https://github.com/openshift/ruby-hello-world.git

#### Create an ImageStream

```
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: my-ruby-image
  namespace: NAMESPACE
```

For Golang APIs, use the following imports
1. `imagev1client https://github.com/openshift/client-go/image/clientset/versioned/typed/image/v1`
2.  `imagev1 "github.com/openshift/api/image/v1"`

As a pre-req,
* This needs kubernetes client-go to be at 0.18.3 #12
* `go get github.com/openshift/client-go@584632b8fc73a646310252d82c303f23e325ab4f`
#### Create a BuildConfig

```
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: my-app-docker-build
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/ruby-hello-world.git'
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: 'my-ruby-image:latest'
```

For Golang APIs, use the following imports
1. `buildv1client https://github.com/openshift/client-go/build/clientset/versioned/typed/image/v1`
2. `buildv1  "github.com/openshift/api/image/v1"`
